INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Downtown Loft', 'Experience urban living at its finest in our stylish Downtown Loft. This modern loft offers contemporary design and is centrally located for easy access to city attractions and nightlife.', 2, 4, 2, true, true, 'HOTEL', 'PERSON', '789 Main Street', 'Metropolis', 'Cityland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Riverside Cabin', 'Escape to nature in our Riverside Cabin. Tucked away by the river, this cozy cabin provides a peaceful retreat with the soothing sounds of nature.', 2, 4, 3, true, true, 'HOTEL', 'PERSON', '123 Riverbank Road', 'Tranquility', 'Greenland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Tranquil Lakehouse', 'Indulge in serenity at our Tranquil Lakehouse. This picturesque retreat is nestled by a pristine lake, offering a perfect blend of relaxation and natural beauty. With a minimum capacity of 4 guests and a maximum capacity of 8, it is an ideal choice for family vacations or a peaceful getaway with friends.', 4, 8, 1, true, true, 'HOTEL', 'PER_NIPERSONGHT', '567 Lakeside Drive', 'Harmony', 'Oasisland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Historic Manor', 'Step back in time at our Historic Manor. This grand estate exudes charm and elegance, offering a unique experience for those who appreciate the beauty of the past. With a minimum capacity of 10 guests and a maximum capacity of 15, it is perfect for special occasions, events, or a luxurious retreat.', 10, 15, 2, true, true, 'HOTEL', 'PERSON', '789 Heritage Lane', 'Heritageville', 'Timeless Kingdom', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Luxury Penthouse Suite', 'Elevate your stay in the city with our Luxury Penthouse Suite. This opulent retreat boasts panoramic city views, exquisite furnishings, and premium amenities. With a minimum capacity of 2 guests and a maximum capacity of 4, it is the epitome of urban sophistication.', 2, 4, 1, true, true, 'HOTEL', 'PERSON', '101 Skyview Avenue', 'Metropolis', 'Cityland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Secluded Mountain Chalet', 'Discover tranquility in our Secluded Mountain Chalet. Tucked away in the hills, this charming chalet offers a cozy escape surrounded by the beauty of nature. With a minimum capacity of 6 guests and a maximum capacity of 10, it is perfect for family gatherings or a peaceful mountain retreat.', 6, 10, 3, true, true, 'ROOM', 'PERSON', '456 Alpine Trail', 'Serenity Peaks', 'Mountaintopia', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Beachfront Bungalow', 'Experience the epitome of coastal living in our Beachfront Bungalow. This charming abode is just steps away from the sandy shores, offering a perfect retreat for beach lovers. With a minimum capacity of 2 guests and a maximum capacity of 4, it is an ideal getaway for couples or a small family.', 2, 4, 2, true, true, 'ROOM', 'PERSON', '789 Shoreline Road', 'Seaside Haven', 'Coastal Paradise', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Urban Oasis Apartment', 'Discover an urban oasis in our stylish apartment. Centrally located, this modern space provides a peaceful retreat in the heart of the city. With a minimum capacity of 1 guest and a maximum capacity of 2, it is perfect for solo travelers or a cozy couple’s getaway.', 1, 2, 1, true, true, 'APARTMENT', 'PERSON', '123 Cityscape Avenue', 'Metropolis', 'Cityland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Charming Vineyard Cottage', 'Escape to the countryside in our Charming Vineyard Cottage. Surrounded by vineyards and rolling hills, this quaint cottage offers a peaceful retreat for wine enthusiasts. With a minimum capacity of 4 guests and a maximum capacity of 6, it is an ideal getaway for a small group or family.', 4, 6, 2, true, true, 'ROOM', 'PERSON', '456 Vineyard Lane', 'Wineville', 'Vineyard Kingdom', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Serenity Beach House', 'Unwind at our Serenity Beach House, a hidden gem on the coast. This spacious beachfront property offers stunning ocean views, making it an ideal retreat for those seeking relaxation by the sea. With a minimum capacity of 6 guests and a maximum capacity of 10, it is perfect for family vacations or a gathering of friends.', 6, 10, 3, true, true, 'ROOM', 'PERSON', '789 Coastal Drive', 'Tranquility Bay', 'Coastal Bliss', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Mountain View Lodge', 'Experience the beauty of nature at our Mountain View Lodge. Surrounded by majestic peaks, this cozy lodge offers a warm and inviting atmosphere. With a minimum capacity of 8 guests and a maximum capacity of 12, it is an excellent choice for group retreats or family gatherings in the mountains.', 8, 12, 4, true, true, 'ROOM', 'PERSON', '123 Mountain Trail', 'Scenic Heights', 'Mountain Valley', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Rustic Farmhouse Retreat', 'Escape to the countryside in our Rustic Farmhouse Retreat. This charming farmhouse, surrounded by rolling fields, offers a peaceful escape from the hustle and bustle. With a minimum capacity of 4 guests and a maximum capacity of 8, it is perfect for a family getaway or a quiet retreat with friends.', 4, 8, 4, true, true, 'ROOM', 'PERSON', '456 Meadow Lane', 'Rural Haven', 'Farmlandia', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Elegant City Townhouse', 'Discover sophistication in our Elegant City Townhouse. Located in a historic district, this beautifully appointed townhouse offers a luxurious urban escape. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a stylish city retreat with friends or family.', 4, 6, 3, true, true, 'ROOM', 'PERSON', '789 Heritage Street', 'Historic District', 'Cityscape', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Oceanfront Paradise Villa', 'Experience the epitome of luxury at our Oceanfront Paradise Villa. This exclusive villa boasts breathtaking ocean views, private amenities, and impeccable design. With a minimum capacity of 8 guests and a maximum capacity of 12, it is an ideal choice for a lavish seaside retreat or special occasions.', 8, 12, 2, true, true, 'APARTMENT', 'PERSON', '101 Coastal Avenue', 'Seaview Haven', 'Coastal Oasis', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Enchanted Forest Cabin', 'Immerse yourself in nature at our Enchanted Forest Cabin. Surrounded by ancient trees and wildlife, this cozy cabin offers a magical escape from the everyday. With a minimum capacity of 2 guests and a maximum capacity of 4, it is perfect for a romantic getaway or a peaceful retreat for nature lovers.', 2, 4, 2, true, true, 'APARTMENT', 'PERSON', '456 Forest Trail', 'Woodland Retreat', 'Natureland', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Skyline View Penthouse', 'Indulge in luxury with our Skyline View Penthouse. Perched high above the city, this penthouse offers stunning panoramic views, modern amenities, and a sophisticated ambiance. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a stylish urban getaway with friends or family.', 4, 6, 1, true, true, 'APARTMENT', 'PERSON', '123 Skyline Avenue', 'Metropolis Heights', 'Cityscape', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Coastal Clifftop Cottage', 'Perched on a coastal cliff, our Clifftop Cottage offers unrivaled views of the ocean. This charming cottage provides a tranquil and romantic escape, ideal for couples seeking a secluded getaway. With a minimum capacity of 2 guests and a maximum capacity of 3, it is a perfect retreat for those desiring privacy and breathtaking scenery.', 2, 3, 1, true, true, 'ROOM', 'ROOM', '789 Cliffside Lane', 'Secluded Cove', 'Coastal Retreat', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Oceanfront Paradise Villa', 'Experience the epitome of luxury at our Oceanfront Paradise Villa. This exclusive villa boasts breathtaking ocean views, private amenities, and impeccable design. With a minimum capacity of 8 guests and a maximum capacity of 12, it is an ideal choice for a lavish seaside retreat or special occasions.', 8, 12, 1, true, true, 'APARTMENT', 'ROOM', '101 Coastal Avenue', 'Seaview Haven', 'Coastal Oasis', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Enchanted Forest Cabin', 'Immerse yourself in nature at our Enchanted Forest Cabin. Surrounded by ancient trees and wildlife, this cozy cabin offers a magical escape from the everyday. With a minimum capacity of 2 guests and a maximum capacity of 4, it is perfect for a romantic getaway or a peaceful retreat for nature lovers.', 2, 4, 1, true, true, 'ROOM', 'ROOM', '456 Forest Trail', 'Woodland Retreat', 'Natureland', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Skyline View Penthouse', 'Indulge in luxury with our Skyline View Penthouse. Perched high above the city, this penthouse offers stunning panoramic views, modern amenities, and a sophisticated ambiance. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a stylish urban getaway with friends or family.', 4, 6, 3, true, true, 'APARTMENT', 'ROOM', '123 Skyline Avenue', 'Metropolis Heights', 'Cityscape', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Coastal Clifftop Cottage', 'Perched on a coastal cliff, our Clifftop Cottage offers unrivaled views of the ocean. This charming cottage provides a tranquil and romantic escape, ideal for couples seeking a secluded getaway. With a minimum capacity of 2 guests and a maximum capacity of 3, it is a perfect retreat for those desiring privacy and breathtaking scenery.', 2, 3, 4, true, true, 'ROOM', 'ROOM', '789 Cliffside Lane', 'Secluded Cove', 'Coastal Retreat', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Sunny Beachfront Villa', 'Bask in the sun at our Sunny Beachfront Villa. This luxurious villa offers direct access to the beach, private pool, and stunning ocean views. With a minimum capacity of 8 guests and a maximum capacity of 12, it is perfect for a tropical getaway or a seaside celebration.', 8, 12, 5, true, true, 'APARTMENT', 'ROOM', '101 Seashore Drive', 'Sunshine Cove', 'Tropical Paradise', '21000', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Urban Loft Living', 'Embrace city life in our Urban Loft Living space. Located in the heart of downtown, this modern loft offers stylish design, convenience, and easy access to the vibrant urban scene. With a minimum capacity of 2 guests and a maximum capacity of 4, it is perfect for urban explorers or a chic city retreat.', 2, 4, 2, true, true, 'APARTMENT', 'PERSON', '456 Downtown Avenue', 'City Center', 'Metropolis', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Majestic Mountain Manor', 'Experience grandeur at our Majestic Mountain Manor. Perched high in the mountains, this elegant manor offers opulent interiors, breathtaking views, and a luxurious escape. With a minimum capacity of 10 guests and a maximum capacity of 15, it is an ideal choice for special occasions or an extravagant mountain retreat.', 10, 15, 3, true, true, 'ROOM', 'ROOM', '789 Summit Lane', 'Mountain Majesty', 'Highland Peaks', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Riverside Haven Cottage', 'Escape to a Riverside Haven in our charming cottage by the river. Surrounded by nature, this cozy retreat offers tranquility and a connection to the outdoors. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a family getaway or a peaceful retreat with friends.', 4, 6, 2, true, true, 'ROOM', 'ROOM', '123 Riverbank Lane', 'Riverside Retreat', 'Natureland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Artisanal Village House', 'Discover the charm of village life in our Artisanal Village House. This rustic yet stylish house offers a unique blend of tradition and comfort. With a minimum capacity of 6 guests and a maximum capacity of 8, it is perfect for those seeking an authentic village experience.', 6, 8, 1, true, true, 'APARTMENT', 'PERSON', '456 Village Square', 'Quaint Village', 'Countryside', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Sunny Beachfront Villa', 'Bask in the sun at our Sunny Beachfront Villa. This luxurious villa offers direct access to the beach, private pool, and stunning ocean views. With a minimum capacity of 8 guests and a maximum capacity of 12, it is perfect for a tropical getaway or a seaside celebration.', 8, 12, 1, true, true, 'ROOM', 'ROOM', '101 Seashore Drive', 'Sunshine Cove', 'Tropical Paradise', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Urban Loft Living', 'Embrace city life in our Urban Loft Living space. Located in the heart of downtown, this modern loft offers stylish design, convenience, and easy access to the vibrant urban scene. With a minimum capacity of 2 guests and a maximum capacity of 4, it is perfect for urban explorers or a chic city retreat.', 2, 4, 2, true, true, 'ROOM', 'PERSON', '456 Downtown Avenue', 'City Center', 'Metropolis', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Majestic Mountain Manor', 'Experience grandeur at our Majestic Mountain Manor. Perched high in the mountains, this elegant manor offers opulent interiors, breathtaking views, and a luxurious escape. With a minimum capacity of 10 guests and a maximum capacity of 15, it is an ideal choice for special occasions or an extravagant mountain retreat.', 10, 15, 3, true, true, 'APARTMENT', 'ROOM', '789 Summit Lane', 'Mountain Majesty', 'Highland Peaks', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Riverside Haven Cottage', 'Escape to a Riverside Haven in our charming cottage by the river. Surrounded by nature, this cozy retreat offers tranquility and a connection to the outdoors. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a family getaway or a peaceful retreat with friends.', 4, 6, 2, true, true, 'APARTMENT', 'ROOM', '123 Riverbank Lane', 'Riverside Retreat', 'Natureland', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Artisanal Village House', 'Discover the charm of village life in our Artisanal Village House. This rustic yet stylish house offers a unique blend of tradition and comfort. With a minimum capacity of 6 guests and a maximum capacity of 8, it is perfect for those seeking an authentic village experience.', 6, 8, 1, true, true, 'HOTEL', 'ROOM', '456 Village Square', 'Quaint Village', 'Countryside', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Sunset Cliff Retreat', 'Unwind at our Sunset Cliff Retreat, a hidden gem perched on the cliffs. This serene retreat offers panoramic views of the ocean and a tranquil atmosphere. With a minimum capacity of 6 guests and a maximum capacity of 10, it is perfect for family vacations or a peaceful escape with friends.', 6, 10, 2, true, true, 'HOTEL', 'PERSON', '101 Cliffside Avenue', 'Seaview Sanctuary', 'Tranquil Isles', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Rustic Mountain Cabin', 'Escape to nature in our Rustic Mountain Cabin. Tucked away in the hills, this charming cabin provides a cozy retreat surrounded by the beauty of the mountains. With a minimum capacity of 2 guests and a maximum capacity of 4, it is perfect for a romantic getaway or a peaceful mountain escape.', 2, 4, 3, true, true, 'APARTMENT', 'PERSON', '456 Mountain Trail', 'Serenity Peaks', 'Highland Valley', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Modern City Apartment', 'Immerse yourself in city living at our Modern City Apartment. Centrally located, this contemporary space offers convenience and comfort. With a minimum capacity of 1 guest and a maximum capacity of 2, it is perfect for solo travelers or a stylish city retreat.', 1, 2, 2, true, true, 'APARTMENT', 'ROOM', '789 Urban Avenue', 'Metropolitan Center', 'Cityscape', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Coastal Cottage Getaway', 'Discover charm by the sea in our Coastal Cottage Getaway. This idyllic cottage offers a peaceful retreat with ocean breezes and sandy shores. With a minimum capacity of 4 guests and a maximum capacity of 6, it is perfect for a family beach vacation or a romantic coastal escape.', 4, 6, 1, true, true, 'HOTEL', 'PERSON', '123 Shoreline Lane', 'Seaside Haven', 'Coastal Paradise', '21000');

INSERT INTO accommodations (name, description, min_guest, max_guest, cancellation_deadline, accepted, manual, accommodation_type, price_per, address, city, country, zip_code)
VALUES ('Luxury Riverside Villa', 'Indulge in luxury at our Riverside Villa. This exquisite villa offers a private oasis by the river with upscale amenities and serene surroundings. With a minimum capacity of 8 guests and a maximum capacity of 12, it is perfect for special occasions or a lavish riverside retreat.', 8, 12, 1, true, true, 'HOTEL', 'ROOM', '456 Riverside Drive', 'Tranquility River', 'Riverland', '21000');
